# Generated by Django 4.2.16 on 2026-04-20 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип колбасы',
                'verbose_name_plural': 'Типы колбас',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kolbasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('weight', models.PositiveIntegerField(help_text='От 50 до 5000 грамм', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='Вес (г)')),
                ('precut', models.BooleanField(default=False, verbose_name='Нарезка')),
                ('num_of_slices', models.PositiveIntegerField(blank=True, help_text='Только если колбаса нарезана', null=True, verbose_name='Количество кусочков')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kolbasas', to='catalog.kind', verbose_name='Тип колбасы')),
            ],
            options={
                'verbose_name': 'Колбаса',
                'verbose_name_plural': 'Колбасы',
                'ordering': ['brand'],
            },
        ),
        migrations.AddConstraint(
            model_name='kolbasa',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 50), ('weight__lte', 5000)), name='weight_between_50_and_5000'),
        ),
    ]
