# Generated by Django 4.2.16 on 2026-04-19 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kolbasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Непустая строка', max_length=100, verbose_name='Бренд')),
                ('kind', models.CharField(choices=[('варёная', 'Варёная'), ('копчёная', 'Копчёная'), ('сырокопчёная', 'Сырокопчёная'), ('полукопчёная', 'Полукопчёная'), ('вяленая', 'Вяленая')], max_length=20, verbose_name='Тип колбасы')),
                ('weight', models.PositiveIntegerField(help_text='От 50 до 5000 грамм', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='Вес (г)')),
                ('precut', models.BooleanField(default=False, verbose_name='Нарезка')),
                ('num_of_slices', models.PositiveIntegerField(blank=True, help_text='Только если колбаса нарезана', null=True, verbose_name='Количество кусочков')),
            ],
            options={
                'verbose_name': 'Колбаса',
                'verbose_name_plural': 'Колбасы',
            },
        ),
    ]
